### ISSUE TITLE
Way to access refreshClusters()?

### ISSUE THREAD

**Issue by monkey121n6** [veitbjarsch/vue-leaflet-markercluster#26] opened 2024-07-02 17:18 UTC
Hey there and thanks for your work!
I for the life of me can't figure out if / how its possible to access the refreshClusters() function. Can you point me in the right direction?

**Comment by veitbjarsch** [comment] 2024-07-02 19:03
Currently you can listen to the `@ready` event which will return you the marker cluster group object. If you like feel free to suggest and implement a more straight forward way.

**Comment by monkey121n6** [comment] 2024-07-03 10:05
Okay, now I have the cluster group object. But it seems like the refreshClusters() function is not exposed?

**Comment by veitbjarsch** [comment] 2024-07-04 21:16
Hey @monkey121n6 sorry for getting back so late. I just tried it and receive the refreshClusters function from the ready event. Can you share some example code. Maybe we can have a look together into it.

**Comment by veitbjarsch** [comment] 2024-07-13 18:28
@monkey121n6 I'm going to close this issue. I could not reproduce the problem. If you still have an issue to access this function feel free to get back to me.

**Comment by monkey121n6** [comment] 2024-07-15 11:12
Hey there, now I am sorry for getting back to you so late! I was on vacation...
Here is an example of what I am doing:

```
<template>
		<l-marker-cluster-group
			:showCoverageOnHover="false"
			:maxClusterRadius="10"
			:iconCreateFunction="clusterIcon"
			ref="markerCluster"
			@ready="onClusterReady"
		>
			<LPlaceMarker
				v-for="place in places"
				:place="place"
				key="`LPlaceMarker-${place.id}`"
				:active="place.id === activePlaceMarker"
			/>
		</l-marker-cluster-group>
</template>

<script>
const clusterGroup = ref(null);
const markerCluster = ref(null);

const onClusterReady = (markerClusterGroup: any) => {
	clusterGroup.value = markerClusterGroup;

	console.log('ClusterGroup:', clusterGroup);
	console.log('markerCluster', markerCluster);
};
</script>
```

I just cant find the refreshClusters function anywhere.. could you give me a hint on how to access it?

Thanks a bunch!

**Comment by veitbjarsch** [comment] 2024-07-15 21:34
Hi, looking into it in the next few days.

**Comment by veitbjarsch** [comment] 2024-07-21 10:43
Here is a project, showing you that the function exists:
https://stackblitz.com/edit/vitejs-vite-dwwyfd

The function is printed into the console as well into the DOM.
Hope this helps.
If you still experience some problems, please create a stackblitz or something similar to show it.

**Comment by veitbjarsch** [comment] 2024-07-27 15:54
@monkey121n6 have you tested it on your side?

**Comment by monkey121n6** [comment] 2024-07-30 10:32
Yes I Just tested it, thanks a lot! I got it to work as intended and am not sure what I did wrong/differently.

**Closed** 2024-07-30 12:33 UTC
